# Docker Compose file to define and run multiple Docker containers for local development.

version: '2'

services:
  # Define the NGINX service
  nginx:
    image: nginx:latest  # Use the latest NGINX image
    container_name: nginx_lb  # Name of the container
    ports:
      - "443:443"  # Map port 443 for HTTPS
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro  # Mount custom NGINX config
      - ./ssl:/etc/nginx/ssl:ro  # Mount SSL directory for certificates
    depends_on:
      - app  # Ensure app service is running before NGINX starts
    networks:
      - nginx_network  # Attach to the shared Docker network

  # Define the application service
  app:
    image: danors/details-app  # Image for the application container
    container_name: details_app  # Name of the container
    environment:
      - PORT=5000  # Environment variable to specify the app's port
    expose:
      - "5000"  # Expose port 5000 within the Docker network
    networks:
      - nginx_network  # Attach to the shared Docker network

# Define a custom bridge network for inter-service communication
networks:
  nginx_network:
    driver: bridge
